Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Controllers/LoginTController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TSCS2.Models;

namespace TSCS2.Controllers
{
    public class LoginTController : Controller
    {
        string cs = @"Data Source=DESKTOP-VJNJ93K\SQLEXPRESS;Initial Catalog=TSCS;Integrated Security=True";
        public ActionResult Index()
        {
            return View();
        }


        // POST: Login/LoginCheck
        [HttpPost]
        public ActionResult LoginCheck(FormCollection collection)
        {
            int matching_result;
            LoginModelT loginModelT = new LoginModelT
            {
                username = collection["username"],
               
                password = collection["password"]
            };
          
            using (SqlConnection conn = new SqlConnection(cs))
            {
                string query = "(select count(*) from loginT where username=@username AND password=@password)";
                SqlCommand sqlCommand = new SqlCommand(query, conn);
                sqlCommand.Parameters.AddWithValue("@username", loginModelT.username);
                sqlCommand.Parameters.AddWithValue("@password", loginModelT.password);

                conn.Open();
                matching_result = (int)sqlCommand.ExecuteScalar();
                //Exexute scalar returns a single value,return type is object,
                //we can convert it at any type.
            }
            if (matching_result > 0)
            {
                int id;
                using (SqlConnection conn = new SqlConnection(cs))
                {
                    DataTable dtblCourse = new DataTable();
                   
                    string query = "select id from loginT where username=@username AND password=@password";
           
                    SqlDataAdapter sqlDa = new SqlDataAdapter(query, conn);
                    sqlDa.SelectCommand.Parameters.AddWithValue("@username", loginModelT.username);
                    sqlDa.SelectCommand.Parameters.AddWithValue("@password", loginModelT.password);
                    sqlDa.Fill(dtblCourse);
                    DataRow row = dtblCourse.Rows[0];
                    id = Convert.ToInt32(row[0].ToString());
                    
                   
                    
                }

                
                Session["id"] = id;
                int ppp = id;
                Session["username"] = loginModelT.username;
                return RedirectToAction("Index", "HomeT");
            }
            else
            {
                return View("WrongLogin");
            }

        }
    }
}

Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Views/Shared/AccessHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="jumbotron" style="min-height:400px;">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Teacher Student Collaboration System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "Index", "About")</li>
                        <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                        <li><span style="color:white;margin-left:240px;"><span class="glyphicon glyphicon-user"></span>@Session["userName"]</span></li>
                        <li><span style="margin-left:50px;"><a href="@Url.Action("Index","LoginT")">Logout</a></span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

    </div>
        

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Teacher Student Collaboration System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>