Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TSCS2.Models;

namespace TSCS2.Controllers
{
    public class LoginController : Controller
    {
        string cs = @"Data Source=DESKTOP-VJNJ93K\SQLEXPRESS;Initial Catalog=TSCS;Integrated Security=True";
        public ActionResult Index()
        {
            
            return View();
        }


        
        // POST: Login/LoginCheck
        [HttpPost]
        public ActionResult LoginCheck(FormCollection collection)
        {
            int matching_result;
            LoginModel loginModel = new LoginModel
            {
                username = collection["username"],
                password = collection["password"]
            };

            using (SqlConnection conn = new SqlConnection(cs))
            {
                string query = "(select count(*) from login where username=@username AND password=@password)";
                SqlCommand sqlCommand = new SqlCommand(query, conn);
                sqlCommand.Parameters.AddWithValue("@username", loginModel.username);
                sqlCommand.Parameters.AddWithValue("@password", loginModel.password);

                conn.Open();
                matching_result = (int)sqlCommand.ExecuteScalar();
                //Exexute scalar returns a single value,return type is object,
                //we can convert it at any type.
            }
            if (matching_result > 0)
            {
                Session["id"] = loginModel.id;
                Session["username"] = loginModel.username;
                return RedirectToAction("startS", "HomeS");
            }
            else
            {
                return View("WrongLogin");
            }

        }
    }
}

Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TSCS2.Models;

namespace TSCS2.Controllers
{
    public class RegistrationController : Controller
    {
        string cs = @"Data Source=DESKTOP-VJNJ93K\SQLEXPRESS;Initial Catalog=TSCS;Integrated Security=True";
        public ActionResult Index()
        {
            return View();
        }


        // POST: Registration/Insert
        [HttpPost]
        public ActionResult Insert(FormCollection collection)
        {
            RegistrationModel registrationModel = new RegistrationModel
            {
                firstname = collection["firstname"],
                lastname = collection["lastname"],
                username = collection["username"],
                password = collection["password"],
                mobile_no = collection["mobile_no"]
            };


            using (SqlConnection conn = new SqlConnection(cs))
            {
                string query = "insert into login values(@firstname,@lastname,@username,@password,@mobile_no)";
                SqlCommand sqlCommand = new SqlCommand(query, conn);
                sqlCommand.Parameters.AddWithValue("@firstname", registrationModel.firstname);
                sqlCommand.Parameters.AddWithValue("@lastname", registrationModel.lastname);
                sqlCommand.Parameters.AddWithValue("@username", registrationModel.username);
                sqlCommand.Parameters.AddWithValue("@password", registrationModel.password);
                sqlCommand.Parameters.AddWithValue("@mobile_no", registrationModel.mobile_no);              

                conn.Open();
                sqlCommand.ExecuteNonQuery();
            }

            return RedirectToAction("Index");

        }


    }
}

Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Views/Login/Index.cshtml
@model TSCS2.Models.LoginModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<!--<a class="btn btn-primary" href="@Url.Action("Index","Registration")">Registration</a>-->

<body style="background-image: url('../../Images/background1.jpg');">
    <div id="login-div" style="margin-top:120px; margin-left:350px;margin-bottom:150px">
        <div style="background-image: url('../../Images/loginback.jpg');padding:20px 0px 20px 40px; margin-right:450px; border-radius:10px">
            @using (Html.BeginForm("LoginCheck", "Login", FormMethod.Post))
            {   
                <div style="margin-left:5px;"><h1>Student Login!</h1></div>
                @Html.AntiForgeryToken()
                
                <div class="form-horizontal">

                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">

                <!--@Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })-->
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control", @placeholder = "User Name" } })
                            @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <!--@Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })-->
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password" } })
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                   
                    <div class="form-group">
                        <div class="col-md-offset-0" style="margin-left:15px;">
                            <input type="submit" value="Login" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

                <div style="margin-top:10px; margin-left:5px;">
                    @Html.ActionLink("Not a register yet, Register Now", "Index", "Registration")
                </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

</body>

Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Views/Login/WrongLogin.cshtml
@{
    ViewBag.Title = "WrongLogin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>WrongLogin</h2>