Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Controllers/RegistrationTController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TSCS2.Models;

namespace TSCS2.Controllers
{
    public class RegistrationTController : Controller
    {
        string cs = @"Data Source=DESKTOP-VJNJ93K\SQLEXPRESS;Initial Catalog=TSCS;Integrated Security=True";
        public ActionResult Index()
        {
            return View();
        }


        // POST: Registration/Insert
        [HttpPost]
        public ActionResult Insert(FormCollection collection)
        {
            RegistrationModelT registrationModelT = new RegistrationModelT
            {
                firstname = collection["firstname"],
                lastname = collection["lastname"],
                username = collection["username"],
                password = collection["password"],
                mobile_no = collection["mobile_no"]
            };


            using (SqlConnection conn = new SqlConnection(cs))
            {
                string query = "insert into loginT values(@firstname,@lastname,@username,@password,@mobile_no)";
                SqlCommand sqlCommand = new SqlCommand(query, conn);
                sqlCommand.Parameters.AddWithValue("@firstname", registrationModelT.firstname);
                sqlCommand.Parameters.AddWithValue("@lastname", registrationModelT.lastname);
                sqlCommand.Parameters.AddWithValue("@username", registrationModelT.username);
                sqlCommand.Parameters.AddWithValue("@password", registrationModelT.password);
                sqlCommand.Parameters.AddWithValue("@mobile_no", registrationModelT.mobile_no);

                conn.Open();
                sqlCommand.ExecuteNonQuery();
            }

            return RedirectToAction("Index");

        }


    }
}

Teacher-Student-Collaboration-system/ISD/TSCS2/TSCS2/Views/RegistrationT/Index.cshtml
@model TSCS2.Models.RegistrationModelT
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body style="background-image: url('../../Images/background1.jpg');">
    <div id="login-div" style="margin-top:120px; margin-left:350px;margin-bottom:150px">
        <div style="background-image: url('../../Images/loginback.jpg');padding:20px 0px 20px 40px; margin-right:450px; border-radius:10px">
            @using (Html.BeginForm("Insert", "RegistrationT", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h2>Teacher Registration</h2>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <!--@Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })-->
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control", @placeholder = "First Name" } })
                            @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <!--@Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })-->
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last Name" } })
                            @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <!--@Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })-->
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control", @placeholder = "User Name" } })
                            @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <!--@Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })-->
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", placeholder = "User Password" } })
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <!--@Html.LabelFor(model => model.mobile_no, htmlAttributes: new { @class = "control-label col-md-2" })-->
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.mobile_no, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mobile no." } })
                            @Html.ValidationMessageFor(model => model.mobile_no, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-0" style="margin-left:15px;">
                            <input type="submit" value="Submit" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to Home", "Index", "Home")
            </div>
        </div>
    </div>
</body>